iabbrev overbracket ⎴
" iabbrev \overparen ⏜
" iabbrev \overbrace ⏞
" iabbrev \underbracket ⎵
" iabbrev \underparen ⏝
" iabbrev \underbrace ⏟
" 
" iabbrev \grave `
" iabbrev \acute ´
" iabbrev \hat ^
" iabbrev \tilde ~
" iabbrev \bar ⁻
" iabbrev \overbar ⁻
" iabbrev \ocirc ∘
" iabbrev \asteraccent *
" 
" iabbrev \lparen (
" iabbrev \lbrack [
" iabbrev \lbrace {
" iabbrev \sqrt √
" iabbrev \cuberoot ∛
" iabbrev \fourthroot ∜
" iabbrev \lceil ⌈
" iabbrev \lfloor ⌊
" iabbrev \ulcorner ⌜
" iabbrev \llcorner ⌞
" iabbrev \lmoustache ⎰
" iabbrev \lbrbrak 〔
" iabbrev \lbag ⟅
" iabbrev \longdivision ⟌
" iabbrev \lBrack ⟦
" iabbrev \langle ⟨
" iabbrev \lAngle ⟪
" iabbrev \lgroup ⟮
" iabbrev \lBrace ⦃
" iabbrev \lParen ⦅
" iabbrev \llparenthesis ⦇
" iabbrev \llangle ⦉
" iabbrev \lbrackubar ⦋
" iabbrev \lbrackultick ⦍
" iabbrev \lbracklltick ⦏
" iabbrev \langledot ⦑
" iabbrev \lparenless ⦓
" iabbrev \Lparengtr ⦕
" iabbrev \lblkbrbrak ⦗
" iabbrev \lvzigzag ⧘
" iabbrev \Lvzigzag ⧚
" iabbrev \lcurvyangle ⧼
" iabbrev \lbrbrak 〔
" iabbrev \Lbrbrak 〘
" 
" iabbrev \rparen )
" iabbrev \rbrack ]
" iabbrev \rbrace }
" iabbrev \rceil ⌉
" iabbrev \rfloor ⌋
" iabbrev \urcorner ⌝
" iabbrev \lrcorner ⌟
" iabbrev \rmoustache ⎱
" iabbrev \rbag ⟆
" iabbrev \rBrack ⟧
" iabbrev \rangle ⟩
" iabbrev \rAngle ⟫
" iabbrev \Rbrbrak 〙
" iabbrev \rgroup ⟯
" iabbrev \rBrace ⦄
" iabbrev \rParen ⦆
" iabbrev \rrparenthesis ⦈
" iabbrev \rrangle ⦊
" iabbrev \rbrackubar ⦌
" iabbrev \rbracklrtick ⦎
" iabbrev \rbrackurtick ⦐
" iabbrev \rangledot ⦒
" iabbrev \rparengtr ⦔
" iabbrev \Rparenless ⦖
" iabbrev \rblkbrbrak ⦘
" iabbrev \rvzigzag ⧙
" iabbrev \Rvzigzag ⧛
" iabbrev \rcurvyangle ⧽
" iabbrev \rbrbrak 〕
" iabbrev \Rbrbrak 〙
" 
" iabbrev \oiint ∯
" iabbrev \oiiint ∰
" iabbrev \Bbbsum ⅀
" iabbrev \intclockwise ∱
" iabbrev \varointclockwise ∳
" iabbrev \ointctrclockwise ∲
" iabbrev \ointctrclockwise ∲
" iabbrev \leftouterjoin ⟕
" iabbrev \rightouterjoin ⟖
" iabbrev \fullouterjoin ⟗
" iabbrev \bigbot ⟘
" iabbrev \bigtop ⟙
" iabbrev \xsol ⧸
" iabbrev \xbsol ⧹
" iabbrev \bigcupdot ⨃
" iabbrev \biguplus ⨄
" iabbrev \bigsqcap ⨅
" iabbrev \bigsqcup ⨆
" iabbrev \conjquant ⨇
" iabbrev \disjquant ⨈
" iabbrev \bigtimes ⨉
" iabbrev \modtwosum ⨊
" iabbrev \sumint ⨋
" iabbrev \iiiint ⨌
" iabbrev \intbar ⨍
" iabbrev \intBar ⨎
" iabbrev \fint ⨏
" iabbrev \cirfnint ⨐
" iabbrev \awint ⨑
" iabbrev \rppolint ⨒
" iabbrev \scpolint ⨓
" iabbrev \npolint ⨔
" iabbrev \pointint ⨕
" iabbrev \sqint ⨖
" iabbrev \intlarhk ⨗
" iabbrev \intx ⨘
" iabbrev \intcap ⨙
" iabbrev \intcup ⨚
" iabbrev \upint ⨛
" iabbrev \lowint ⨜
" iabbrev \Join ⨝
" iabbrev \bigtriangleleft ⨞
" iabbrev \zcmp ⨟
" iabbrev \zpipe ⨠
" iabbrev \zproject ⨡
" iabbrev \biginterleave ⫼
" iabbrev \bigtalloblong ⫿
" 
" iabbrev \plus +
" iabbrev \pm ±
" iabbrev \cdotp ·
" iabbrev \times ×
" iabbrev \div ÷
" iabbrev \dagger †
" iabbrev \ddagger ‡
" iabbrev \smblkcircle •
" iabbrev \tieconcat ⁀
" iabbrev \fracslash ⁄
" iabbrev \upand ⅋
" iabbrev \minus −
" iabbrev \mp ∓
" iabbrev \dotplus ∔
" iabbrev \divslash ∕
" iabbrev \smallsetminus ∖
" iabbrev \ast ∗
" iabbrev \vysmwhtcircle ∘
" iabbrev \vysmblkcircle ∙
" iabbrev \wedge ∧
" iabbrev \vee ∨
" iabbrev \cap ∩
" iabbrev \cup ∪
" iabbrev \dotminus ∸
" iabbrev \invlazys ∾
" iabbrev \wr ≀
" iabbrev \cupleftarrow ⊌
" iabbrev \cupdot ⊍
" iabbrev \uplus ⊎
" iabbrev \sqcap ⊓
" iabbrev \sqcup ⊔
" iabbrev \oplus ⊕
" iabbrev \ominus ⊖
" iabbrev \otimes ⊗
" iabbrev \oslash ⊘
" iabbrev \odot ⊙
" 
" iabbrev \circledcirc ⊚
" iabbrev \circledast ⊛
" iabbrev \circledequal ⊜
" iabbrev \circleddash ⊝
" iabbrev \boxplus ⊞
" iabbrev \boxminus ⊟
" iabbrev \boxtimes ⊠
" iabbrev \boxdot ⊡
" iabbrev \intercal ⊺
" iabbrev \veebar ⊻
" iabbrev \barwedge ⊼
" iabbrev \barvee ⊽
" iabbrev \smwhtdiamond ⋄
" iabbrev \cdot ⋅
" iabbrev \star ⋆
" iabbrev \divideontimes ⋇
" iabbrev \ltimes ⋉
" iabbrev \rtimes ⋊
" iabbrev \leftthreetimes ⋋
" iabbrev \rightthreetimes ⋌
" iabbrev \curlyvee ⋎
" iabbrev \curlywedge ⋏
" iabbrev \Cap ⋒
" iabbrev \Cup ⋓
" iabbrev \varbarwedge ⌅
" iabbrev \vardoublebarwedge ⌆
" iabbrev \obar ⌽
" iabbrev \bigtriangleup △
" iabbrev \triangleright ▷
" iabbrev \triangleleft ◁
" iabbrev \mdlgwhtcircle ○
" iabbrev \boxbar ◫
" iabbrev \veedot ⟇
" iabbrev \wedgedot ⟑
" iabbrev \lozengeminus ⟠
" iabbrev \concavediamond ⟡
" iabbrev \concavediamondtickleft ⟢
" iabbrev \concavediamondtickright ⟣
" iabbrev \whitesquaretickleft ⟤
" iabbrev \whitesquaretickright ⟥
" iabbrev \typecolon ⦂
" iabbrev \circlehbar ⦵
" iabbrev \circledvert ⦶
" iabbrev \circledparallel ⦷
" iabbrev \obslash ⦸
" iabbrev \operp ⦹
" iabbrev \olessthan ⧀
" iabbrev \ogreaterthan ⧁
" iabbrev \boxdiag ⧄
" 
" iabbrev \boxbslash ⧅
" iabbrev \boxast ⧆
" iabbrev \boxcircle ⧇
" iabbrev \boxbox ⧈
" iabbrev \triangleserifs ⧍
" iabbrev \hourglass ⧖
" iabbrev \blackhourglass ⧗
" iabbrev \shuffle ⧢
" iabbrev \mdlgblklozenge ⧫
" iabbrev \setminus ⧵
" iabbrev \dsol ⧶
" iabbrev \rsolbar ⧷
" iabbrev \doubleplus ⧺
" iabbrev \tripleplus ⧻
" iabbrev \tplus ⧾
" iabbrev \tminus ⧿
" iabbrev \ringplus ⨢
" iabbrev \plushat ⨣
" iabbrev \simplus ⨤
" iabbrev \plusdot ⨥
" iabbrev \plussim ⨦
" iabbrev \plussubtwo ⨧
" iabbrev \plustrif ⨨
" iabbrev \commaminus ⨩
" iabbrev \minusdot ⨪
" iabbrev \minusfdots ⨫
" iabbrev \minusrdots ⨬
" iabbrev \opluslhrim ⨭
" iabbrev \oplusrhrim ⨮
" iabbrev \vectimes ⨯
" iabbrev \dottimes ⨰
" iabbrev \timesbar ⨱
" iabbrev \btimes ⨲
" iabbrev \smashtimes ⨳
" iabbrev \otimeslhrim ⨴
" iabbrev \otimesrhrim ⨵
" iabbrev \otimeshat ⨶
" iabbrev \Otimes ⨷
" iabbrev \odiv ⨸
" iabbrev \triangleplus ⨹
" iabbrev \triangleminus ⨺
" iabbrev \triangletimes ⨻
" iabbrev \intprod ⨼
" iabbrev \intprodr ⨽
" iabbrev \fcmp ⨾
" iabbrev \amalg ⨿
" iabbrev \capdot ⩀
" iabbrev \uminus ⩁
" iabbrev \barcup ⩂
" iabbrev \barcap ⩃
" 
" iabbrev \capwedge ⩄
" iabbrev \cupvee ⩅
" iabbrev \cupovercap ⩆
" iabbrev \capovercup ⩇
" iabbrev \cupbarcap ⩈
" iabbrev \capbarcup ⩉
" iabbrev \twocups ⩊
" iabbrev \twocaps ⩋
" iabbrev \closedvarcup ⩌
" iabbrev \closedvarcap ⩍
" iabbrev \Sqcap ⩎
" iabbrev \Sqcup ⩏
" iabbrev \closedvarcupsmashprod ⩐
" iabbrev \wedgeodot ⩑
" iabbrev \veeodot ⩒
" iabbrev \Wedge ⩓
" iabbrev \Vee ⩔
" iabbrev \wedgeonwedge ⩕
" iabbrev \veeonvee ⩖
" iabbrev \bigslopedvee ⩗
" iabbrev \bigslopedwedge ⩘
" iabbrev \wedgemidvert ⩚
" iabbrev \veemidvert ⩛
" iabbrev \midbarwedge ⩜
" iabbrev \midbarvee ⩝
" iabbrev \doublebarwedge ⩞
" iabbrev \wedgebar ⩟
" iabbrev \wedgedoublebar ⩠
" iabbrev \varveebar ⩡
" iabbrev \doublebarvee ⩢
" iabbrev \veedoublebar ⩣
" iabbrev \dsub ⩤
" iabbrev \rsub ⩥
" iabbrev \eqqplus ⩱
" iabbrev \pluseqq ⩲
" iabbrev \interleave ⫴
" iabbrev \nhVvert ⫵
" iabbrev \threedotcolon ⫶
" iabbrev \trslash ⫻
" iabbrev \sslash ⫽
" iabbrev \talloblong ⫾
" 
" iabbrev \octothorpe #
" iabbrev \mathdollar $
" iabbrev \percent %
" iabbrev \ampersand &
" iabbrev \period .
" iabbrev \mathslash /
" iabbrev \question ?
" iabbrev \atsign @
" iabbrev \backslash \
" iabbrev \sterling £
" iabbrev \yen ¥
" iabbrev \neg ¬
" iabbrev \Zbar Ƶ
" iabbrev \upoldKoppa Ϙ
" iabbrev \upoldkoppa ϙ
" iabbrev \upbackepsilon ϶
" iabbrev \horizbar ―
" iabbrev \twolowline ‗
" iabbrev \enleadertwodots ‥
" iabbrev \unicodeellipsis …
" iabbrev \prime ′
" iabbrev \dprime ″
" iabbrev \trprime ‴
" iabbrev \backprime ‵
" iabbrev \backdprime ‶
" iabbrev \backtrprime ‷
" iabbrev \caretinsert ‸
" iabbrev \Exclam ‼
" iabbrev \hyphenbullet ⁃
" iabbrev \Question ⁇
" iabbrev \qprime ⁗
" iabbrev \euro €
" iabbrev \enclosecircle  ⃝
" iabbrev \enclosesquare  ⃞
" iabbrev \enclosediamond  ⃟
" iabbrev \enclosetriangle  ⃤
" iabbrev \Eulerconst ℇ
" iabbrev \Planckconst ℎ
" iabbrev \mho ℧
" iabbrev \Finv Ⅎ
" iabbrev \Bbbpi ℼ
" iabbrev \Game ⅁
" iabbrev \sansLturned ⅂
" iabbrev \sansLmirrored ⅃
" iabbrev \Yup ⅄
" iabbrev \mitBbbD ⅅ
" iabbrev \mitBbbd ⅆ
" 
" iabbrev \mitBbbe ⅇ
" iabbrev \mitBbbi ⅈ
" iabbrev \mitBbbj ⅉ
" iabbrev \PropertyLine ⅊
" iabbrev \updownarrowbar ↨
" iabbrev \linefeed ↴
" iabbrev \carriagereturn ↵
" iabbrev \barovernorthwestarrow ↸
" iabbrev \barleftarrowrightarrowbar ↹
" iabbrev \acwopencirclearrow ↺
" iabbrev \cwopencirclearrow ↻
" iabbrev \nHuparrow ⇞
" iabbrev \nHdownarrow ⇟
" iabbrev \leftdasharrow ⇠
" iabbrev \updasharrow ⇡
" iabbrev \rightdasharrow ⇢
" iabbrev \downdasharrow ⇣
" iabbrev \leftwhitearrow ⇦
" iabbrev \upwhitearrow ⇧
" iabbrev \rightwhitearrow ⇨
" iabbrev \downwhitearrow ⇩
" iabbrev \whitearrowupfrombar ⇪
" iabbrev \forall ∀
" iabbrev \complement ∁
" iabbrev \exists ∃
" iabbrev \nexists ∄
" iabbrev \varnothing ∅
" iabbrev \increment ∆
" iabbrev \QED ∎
" iabbrev \infty ∞
" iabbrev \rightangle ∟
" iabbrev \angle ∠
" iabbrev \measuredangle ∡
" iabbrev \sphericalangle ∢
" iabbrev \therefore ∴
" iabbrev \because ∵
" iabbrev \sinewave ∿
" iabbrev \top ⊤
" iabbrev \bot ⊥
" iabbrev \hermitmatrix ⊹
" iabbrev \measuredrightangle ⊾
" iabbrev \varlrtriangle ⊿
" iabbrev \unicodecdots ⋯
" iabbrev \diameter ⌀
" iabbrev \house ⌂
" iabbrev \invnot ⌐
" iabbrev \sqlozenge ⌑
" iabbrev \profline ⌒
" iabbrev \profsurf ⌓
" iabbrev \viewdata ⌗
" 
" iabbrev \turnednot ⌙
" iabbrev \inttop ⌠
" iabbrev \intbottom ⌡
" iabbrev \varhexagonlrbonds ⌬
" iabbrev \conictaper ⌲
" iabbrev \topbot ⌶
" iabbrev \APLnotbackslash ⍀
" iabbrev \APLboxupcaret ⍓
" iabbrev \APLboxquestion ⍰
" iabbrev \rangledownzigzagarrow ⍼
" iabbrev \hexagon ⎔
" iabbrev \lparenuend ⎛
" iabbrev \lparenextender ⎜
" iabbrev \lparenlend ⎝
" iabbrev \rparenuend ⎞
" iabbrev \rparenextender ⎟
" iabbrev \rparenlend ⎠
" iabbrev \lbrackuend ⎡
" iabbrev \lbrackextender ⎢
" iabbrev \lbracklend ⎣
" iabbrev \rbrackuend ⎤
" iabbrev \rbrackextender ⎥
" iabbrev \rbracklend ⎦
" iabbrev \lbraceuend ⎧
" iabbrev \lbracemid ⎨
" iabbrev \lbracelend ⎩
" 
" iabbrev \rbraceuend ⎫
" iabbrev \rbracemid ⎬
" iabbrev \rbracelend ⎭
" iabbrev \intextender ⎮
" iabbrev \harrowextender ⎯
" iabbrev \sumtop ⎲
" iabbrev \sumbottom ⎳
" iabbrev \bbrktbrk ⎶
" iabbrev \sqrtbottom ⎷
" iabbrev \lvboxline ⎸
" iabbrev \rvboxline ⎹
" iabbrev \varcarriagereturn ⏎
" iabbrev \obrbrak ⏠
" iabbrev \ubrbrak ⏡
" iabbrev \trapezium ⏢
" iabbrev \benzenr ⏣
" iabbrev \strns ⏤
" iabbrev \fltns ⏥
" iabbrev \accurrent ⏦
" iabbrev \elinters ⏧
" iabbrev \blanksymbol ␢
" iabbrev \mathvisiblespace ␣
" iabbrev \bdtriplevdash ┆
" iabbrev \blockuphalf ▀
" iabbrev \blocklowhalf ▄
" iabbrev \blockfull █
" iabbrev \blocklefthalf ▌
" iabbrev \blockrighthalf ▐
" iabbrev \blockqtrshaded ░
" iabbrev \blockhalfshaded ▒
" iabbrev \blockthreeqtrshaded ▓
" iabbrev \mdlgblksquare ■
" iabbrev \mdlgwhtsquare □
" iabbrev \squoval ▢
" iabbrev \blackinwhitesquare ▣
" iabbrev \squarehfill ▤
" iabbrev \squarevfill ▥
" iabbrev \squarehvfill ▦
" iabbrev \squarenwsefill ▧
" iabbrev \squareneswfill ▨
" 
" iabbrev \squarecrossfill ▩
" iabbrev \smblksquare ▪
" iabbrev \smwhtsquare ▫
" iabbrev \hrectangleblack ▬
" iabbrev \hrectangle ▭
" iabbrev \vrectangleblack ▮
" iabbrev \vrectangle ▯
" iabbrev \parallelogramblack ▰
" iabbrev \parallelogram ▱
" iabbrev \bigblacktriangleup ▲
" iabbrev \blacktriangle ▴
" iabbrev \blacktriangleright ▶
" iabbrev \smallblacktriangleright ▸
" iabbrev \smalltriangleright ▹
" iabbrev \blackpointerright ►
" iabbrev \whitepointerright ▻
" iabbrev \bigblacktriangledown ▼
" iabbrev \bigtriangledown ▽
" iabbrev \blacktriangledown ▾
" iabbrev \triangledown ▿
" iabbrev \blacktriangleleft ◀
" iabbrev \smallblacktriangleleft ◂
" iabbrev \smalltriangleleft ◃
" iabbrev \blackpointerleft ◄
" iabbrev \whitepointerleft ◅
" iabbrev \mdlgblkdiamond ◆
" iabbrev \mdlgwhtdiamond ◇
" iabbrev \blackinwhitediamond ◈
" iabbrev \fisheye ◉
" iabbrev \mdlgwhtlozenge ◊
" iabbrev \dottedcircle ◌
" iabbrev \circlevertfill ◍
" iabbrev \bullseye ◎
" iabbrev \mdlgblkcircle ●
" iabbrev \circlelefthalfblack ◐
" iabbrev \circlerighthalfblack ◑
" iabbrev \circlebottomhalfblack ◒
" iabbrev \circletophalfblack ◓
" iabbrev \circleurquadblack ◔
" iabbrev \blackcircleulquadwhite ◕
" iabbrev \blacklefthalfcircle ◖
" iabbrev \blackrighthalfcircle ◗
" iabbrev \inversebullet ◘
" iabbrev \inversewhitecircle ◙
" iabbrev \invwhiteupperhalfcircle ◚
" iabbrev \invwhitelowerhalfcircle ◛
" iabbrev \ularc ◜
" iabbrev \urarc ◝
" iabbrev \lrarc ◞
" iabbrev \llarc ◟
" 
" iabbrev \topsemicircle ◠
" iabbrev \botsemicircle ◡
" iabbrev \lrblacktriangle ◢
" iabbrev \llblacktriangle ◣
" iabbrev \ulblacktriangle ◤
" iabbrev \urblacktriangle ◥
" iabbrev \smwhtcircle ◦
" iabbrev \squareleftblack ◧
" iabbrev \squarerightblack ◨
" iabbrev \squareulblack ◩
" iabbrev \squarelrblack ◪
" iabbrev \trianglecdot ◬
" iabbrev \triangleleftblack ◭
" iabbrev \trianglerightblack ◮
" iabbrev \lgwhtcircle ◯
" iabbrev \squareulquad ◰
" iabbrev \squarellquad ◱
" iabbrev \squarelrquad ◲
" iabbrev \squareurquad ◳
" iabbrev \circleulquad ◴
" iabbrev \circlellquad ◵
" iabbrev \circlelrquad ◶
" iabbrev \circleurquad ◷
" iabbrev \ultriangle ◸
" iabbrev \urtriangle ◹
" iabbrev \lltriangle ◺
" iabbrev \mdwhtsquare ◻
" iabbrev \mdblksquare ◼
" iabbrev \mdsmwhtsquare ◽
" iabbrev \mdsmblksquare ◾
" iabbrev \lrtriangle ◿
" iabbrev \bigstar ★
" iabbrev \bigwhitestar ☆
" iabbrev \astrosun ☉
" iabbrev \danger ☡
" iabbrev \blacksmiley ☻
" iabbrev \sun ☼
" iabbrev \rightmoon ☽
" iabbrev \leftmoon ☾
" iabbrev \female ♀
" iabbrev \male ♂
" iabbrev \spadesuit ♠
" iabbrev \heartsuit ♡
" iabbrev \diamondsuit ♢
" iabbrev \clubsuit ♣
" iabbrev \varspadesuit ♤
" iabbrev \varheartsuit ♥
" iabbrev \vardiamondsuit ♦
" iabbrev \varclubsuit ♧
" iabbrev \quarternote ♩
" 
" iabbrev \eighthnote ♪
" iabbrev \twonotes ♫
" iabbrev \flat ♭
" iabbrev \natural ♮
" iabbrev \sharp ♯
" iabbrev \acidfree ♾
" iabbrev \dicei ⚀
" iabbrev \diceii ⚁
" iabbrev \diceiii ⚂
" iabbrev \diceiv ⚃
" iabbrev \dicev ⚄
" iabbrev \dicevi ⚅
" iabbrev \circledrightdot ⚆
" iabbrev \circledtwodots ⚇
" iabbrev \blackcircledrightdot ⚈
" iabbrev \blackcircledtwodots ⚉
" iabbrev \Hermaphrodite ⚥ 
" iabbrev \mdwhtcircle ⚪
" iabbrev \mdblkcircle ⚫
" iabbrev \mdsmwhtcircle ⚬
" iabbrev \neuter ⚲
" iabbrev \checkmark ✓
" iabbrev \maltese ✠
" iabbrev \circledstar ✪
" iabbrev \varstar ✶
" iabbrev \dingasterisk ✽
" iabbrev \draftingarrow ➛
" iabbrev \threedangle ⟀
" iabbrev \whiteinwhitetriangle ⟁
" iabbrev \subsetcirc ⟃
" iabbrev \supsetcirc ⟄
" iabbrev \diamondcdot ⟐
" iabbrev \rdiagovfdiag ⤫
" iabbrev \fdiagovrdiag ⤬
" iabbrev \seovnearrow ⤭
" iabbrev \neovsearrow ⤮
" iabbrev \fdiagovnearrow ⤯
" iabbrev \rdiagovsearrow ⤰
" iabbrev \neovnwarrow ⤱
" iabbrev \nwovnearrow ⤲
" iabbrev \uprightcurvearrow ⤴
" iabbrev \downrightcurvedarrow ⤵
" iabbrev \mdsmblkcircle ⦁
" iabbrev \fourvdots ⦙
" iabbrev \vzigzag ⦚
" iabbrev \measuredangleleft ⦛
" iabbrev \rightanglesqr ⦜
" iabbrev \rightanglemdot ⦝
" iabbrev \angles ⦞
" iabbrev \angdnr ⦟
" 
" iabbrev \gtlpar ⦠
" iabbrev \sphericalangleup ⦡
" iabbrev \turnangle ⦢
" iabbrev \revangle ⦣
" iabbrev \angleubar ⦤
" iabbrev \revangleubar ⦥
" iabbrev \wideangledown ⦦
" iabbrev \wideangleup ⦧
" iabbrev \measanglerutone ⦨
" iabbrev \measanglelutonw ⦩
" iabbrev \measanglerdtose ⦪
" iabbrev \measangleldtosw ⦫
" iabbrev \measangleurtone ⦬
" iabbrev \measangleultonw ⦭
" iabbrev \measangledrtose ⦮
" iabbrev \measangledltosw ⦯
" iabbrev \revemptyset ⦰
" iabbrev \emptysetobar ⦱
" iabbrev \emptysetocirc ⦲
" iabbrev \emptysetoarr ⦳
" iabbrev \emptysetoarrl ⦴
" iabbrev \obot ⦺
" iabbrev \olcross ⦻
" iabbrev \odotslashdot ⦼
" iabbrev \uparrowoncircle ⦽
" iabbrev \circledwhitebullet ⦾
" iabbrev \circledbullet ⦿
" iabbrev \cirscir ⧂
" iabbrev \cirE ⧃
" iabbrev \boxonbox ⧉
" iabbrev \triangleodot ⧊
" iabbrev \triangleubar ⧋
" iabbrev \triangles ⧌
" iabbrev \iinfin ⧜
" iabbrev \tieinfty ⧝
" iabbrev \nvinfty ⧞
" iabbrev \laplac ⧠
" iabbrev \thermod ⧧
" iabbrev \downtriangleleftblack ⧨
" iabbrev \downtrianglerightblack ⧩
" iabbrev \blackdiamonddownarrow ⧪
" iabbrev \circledownarrow ⧬
" iabbrev \blackcircledownarrow ⧭
" iabbrev \errbarsquare ⧮
" iabbrev \errbarblacksquare ⧯
" iabbrev \errbardiamond ⧰
" iabbrev \errbarblackdiamond ⧱
" iabbrev \errbarcircle ⧲
" iabbrev \errbarblackcircle ⧳
" iabbrev \perps ⫡
" iabbrev \topcir ⫱
" iabbrev \squaretopblack ⬒
" iabbrev \squarebotblack ⬓
" iabbrev \squareurblack ⬔
" iabbrev \squarellblack ⬕
" iabbrev \diamondleftblack ⬖
" iabbrev \diamondrightblack ⬗
" iabbrev \diamondtopblack ⬘
" iabbrev \diamondbotblack ⬙
" iabbrev \dottedsquare ⬚
" iabbrev \lgblksquare ⬛
" iabbrev \lgwhtsquare ⬜
" iabbrev \vysmblksquare ⬝
" iabbrev \vysmwhtsquare ⬞
" iabbrev \pentagonblack ⬟
" iabbrev \pentagon ⬠
" iabbrev \varhexagon ⬡
" iabbrev \varhexagonblack ⬢
" iabbrev \hexagonblack ⬣
" iabbrev \lgblkcircle ⬤
" iabbrev \mdblkdiamond ⬥
" iabbrev \mdwhtdiamond ⬦
" iabbrev \mdblklozenge ⬧
" iabbrev \mdwhtlozenge ⬨
" iabbrev \smblkdiamond ⬩
" iabbrev \smblklozenge ⬪
" iabbrev \smwhtlozenge ⬫
" iabbrev \blkhorzoval ⬬
" iabbrev \whthorzoval ⬭
" iabbrev \blkvertoval ⬮
" iabbrev \whtvertoval ⬯
" iabbrev \medwhitestar ⭐
" iabbrev \medblackstar ⭑
" iabbrev \smwhitestar ⭒
" iabbrev \rightpentagonblack ⭓
" iabbrev \rightpentagon ⭔
" iabbrev \postalmark 〒
" iabbrev \hzigzag 〰
" 
" iabbrev \mbfzero 𝟎
" iabbrev \mbfone 𝟏
" iabbrev \mbftwo 𝟐
" iabbrev \mbfthree 𝟑
" iabbrev \mbffour 𝟒
" iabbrev \mbffive 𝟓
" iabbrev \mbfsix 𝟔
" iabbrev \mbfseven 𝟕
" iabbrev \mbfeight 𝟖
" iabbrev \mbfnine 𝟗
" 
" iabbrev \Bbbzero 𝟘
" iabbrev \Bbbone 𝟙
" iabbrev \Bbbtwo 𝟚
" iabbrev \Bbbthree 𝟛
" iabbrev \Bbbfour 𝟜
" iabbrev \Bbbfive 𝟝
" iabbrev \Bbbsix 𝟞
" iabbrev \Bbbseven 𝟟
" iabbrev \Bbbeight 𝟠
" iabbrev \Bbbnine 𝟡
" 
" iabbrev \msanszero 𝟢
" iabbrev \msansone 𝟣
" iabbrev \msanstwo 𝟤
" iabbrev \msansthree 𝟥
" iabbrev \msansfour 𝟦
" iabbrev \msansfive 𝟧
" iabbrev \msanssix 𝟨
" iabbrev \msansseven 𝟩
" iabbrev \msanseight 𝟪
" iabbrev \msansnine 𝟫
" 
" iabbrev \mbfsanszero 𝟬
" iabbrev \mbfsansone 𝟭
" iabbrev \mbfsanstwo 𝟮
" iabbrev \mbfsansthree 𝟯
" iabbrev \mbfsansfour 𝟰
" iabbrev \mbfsansfive 𝟱
" iabbrev \mbfsanssix 𝟲
" iabbrev \mbfsansseven 𝟳
" iabbrev \mbfsanseight 𝟴
" iabbrev \mbfsansnine 𝟵
" 
" iabbrev \mttzero 𝟶
" iabbrev \mttone 𝟷
" iabbrev \mtttwo 𝟸
" iabbrev \mttthree 𝟹
" iabbrev \mttfour 𝟺
" iabbrev \mttfive 𝟻
" iabbrev \mttsix 𝟼
" iabbrev \mttseven 𝟽
" iabbrev \mtteight 𝟾
" iabbrev \mttnine 𝟿
" 
" iabbrev \less <
" iabbrev \equal =
" iabbrev \greater >
" iabbrev \closure ⁐
" iabbrev \leftarrow ←
" iabbrev \uparrow ↑
" iabbrev \rightarrow →
" iabbrev \downarrow ↓
" iabbrev \leftrightarrow ↔
" iabbrev \updownarrow ↕
" iabbrev \nwarrow ↖
" iabbrev \nearrow ↗
" iabbrev \searrow ↘
" iabbrev \swarrow ↙
" iabbrev \nleftarrow ↚
" iabbrev \nrightarrow ↛
" iabbrev \leftwavearrow ↜
" iabbrev \rightwavearrow ↝
" iabbrev \twoheadleftarrow ↞
" iabbrev \twoheaduparrow ↟
" iabbrev \twoheadrightarrow ↠
" iabbrev \twoheaddownarrow ↡
" iabbrev \leftarrowtail ↢
" iabbrev \rightarrowtail ↣
" iabbrev \mapsfrom ↤
" iabbrev \mapsup ↥
" iabbrev \mapsto ↦
" iabbrev \mapsdown ↧
" iabbrev \hookleftarrow ↩
" iabbrev \hookrightarrow ↪
" iabbrev \looparrowleft ↫
" iabbrev \looparrowright ↬
" 
" iabbrev \leftrightsquigarrow ↭
" iabbrev \nleftrightarrow ↮
" iabbrev \downzigzagarrow ↯
" iabbrev \Lsh ↰
" iabbrev \Rsh ↱
" iabbrev \Ldsh ↲
" iabbrev \Rdsh ↳
" iabbrev \curvearrowleft ↶
" iabbrev \curvearrowright ↷
" iabbrev \leftharpoonup ↼
" iabbrev \leftharpoondown ↽
" iabbrev \upharpoonright ↾
" iabbrev \upharpoonleft ↿
" iabbrev \rightharpoonup ⇀
" iabbrev \rightharpoondown ⇁
" 
" iabbrev \downharpoonright ⇂
" iabbrev \downharpoonleft ⇃
" iabbrev \rightleftarrows ⇄
" iabbrev \updownarrows ⇅
" iabbrev \leftrightarrows ⇆
" iabbrev \leftleftarrows ⇇
" iabbrev \upuparrows ⇈
" iabbrev \rightrightarrows ⇉
" iabbrev \downdownarrows ⇊
" iabbrev \leftrightharpoons ⇋
" iabbrev \rightleftharpoons ⇌
" iabbrev \nLeftarrow ⇍
" iabbrev \nLeftrightarrow ⇎
" iabbrev \nRightarrow ⇏
" iabbrev \Leftarrow ⇐
" iabbrev \Uparrow ⇑
" iabbrev \Rightarrow ⇒
" iabbrev \Downarrow ⇓
" iabbrev \Leftrightarrow ⇔
" iabbrev \Updownarrow ⇕
" iabbrev \Nwarrow ⇖
" iabbrev \Nearrow ⇗
" iabbrev \Searrow ⇘
" iabbrev \Swarrow ⇙
" iabbrev \Lleftarrow ⇚
" iabbrev \Rrightarrow ⇛
" iabbrev \leftsquigarrow ⇜
" iabbrev \rightsquigarrow ⇝
" iabbrev \barleftarrow ⇤
" iabbrev \rightarrowbar ⇥
" iabbrev \circleonrightarrow ⇴
" iabbrev \downuparrows ⇵
" iabbrev \rightthreearrows ⇶
" iabbrev \nvleftarrow ⇷
" iabbrev \nvrightarrow ⇸
" iabbrev \nvleftrightarrow ⇹
" iabbrev \nVleftarrow ⇺
" iabbrev \nVrightarrow ⇻
" iabbrev \nVleftrightarrow ⇼
" iabbrev \leftarrowtriangle ⇽
" iabbrev \rightarrowtriangle ⇾
" iabbrev \leftrightarrowtriangle ⇿
" iabbrev \in ∈
" iabbrev \notin ∉
" iabbrev \smallin ∊
" iabbrev \ni ∋
" iabbrev \nni ∌
" iabbrev \smallni ∍
" iabbrev \propto ∝
" iabbrev \mid ∣
" 
" iabbrev \nmid ∤
" iabbrev \parallel ∥
" iabbrev \nparallel ∦
" iabbrev \mathratio ∶
" iabbrev \Colon ∷
" iabbrev \dashcolon ∹
" iabbrev \dotsminusdots ∺
" iabbrev \kernelcontraction ∻
" iabbrev \sim ∼
" iabbrev \backsim ∽
" iabbrev \nsim ≁
" iabbrev \eqsim ≂
" iabbrev \simeq ≃
" iabbrev \nsime ≄
" iabbrev \cong ≅
" iabbrev \simneqq ≆
" iabbrev \ncong ≇
" iabbrev \approx ≈
" iabbrev \napprox ≉
" iabbrev \approxeq ≊
" iabbrev \approxident ≋
" iabbrev \backcong ≌
" iabbrev \asymp ≍
" iabbrev \Bumpeq ≎
" iabbrev \bumpeq ≏
" iabbrev \doteq ≐
" iabbrev \Doteq ≑
" iabbrev \fallingdotseq ≒
" iabbrev \risingdotseq ≓
" iabbrev \coloneq ≔
" iabbrev \eqcolon ≕
" iabbrev \eqcirc ≖
" iabbrev \circeq ≗
" iabbrev \arceq ≘
" iabbrev \wedgeq ≙
" iabbrev \veeeq ≚
" iabbrev \stareq ≛
" iabbrev \triangleq ≜
" iabbrev \eqdef ≝
" iabbrev \measeq ≞
" iabbrev \questeq ≟
" iabbrev \ne ≠
" iabbrev \equiv ≡
" iabbrev \nequiv ≢
" iabbrev \Equiv ≣
" iabbrev \leq ≤
" iabbrev \geq ≥
" iabbrev \leqq ≦
" iabbrev \geqq ≧
" iabbrev \lneqq ≨
" 
" iabbrev \gneqq ≩
" iabbrev \ll ≪
" iabbrev \gg ≫
" iabbrev \between ≬
" iabbrev \nasymp ≭
" iabbrev \nless ≮
" iabbrev \ngtr ≯
" iabbrev \nleq ≰
" iabbrev \ngeq ≱
" iabbrev \lesssim ≲
" iabbrev \gtrsim ≳
" iabbrev \nlesssim ≴
" iabbrev \ngtrsim ≵
" iabbrev \lessgtr ≶
" iabbrev \gtrless ≷
" iabbrev \nlessgtr ≸
" iabbrev \ngtrless ≹
" iabbrev \prec ≺
" iabbrev \succ ≻
" iabbrev \preccurlyeq ≼
" iabbrev \succcurlyeq ≽
" iabbrev \precsim ≾
" iabbrev \succsim ≿
" iabbrev \nprec ⊀
" iabbrev \nsucc ⊁
" iabbrev \subset ⊂
" iabbrev \supset ⊃
" iabbrev \nsubset ⊄
" iabbrev \nsupset ⊅
" iabbrev \subseteq ⊆
" iabbrev \supseteq ⊇
" iabbrev \nsubseteq ⊈
" iabbrev \nsupseteq ⊉
" iabbrev \subsetneq ⊊
" iabbrev \supsetneq ⊋
" iabbrev \sqsubset ⊏
" iabbrev \sqsupset ⊐
" iabbrev \sqsubseteq ⊑
" iabbrev \sqsupseteq ⊒
" iabbrev \vdash ⊢
" iabbrev \dashv ⊣
" iabbrev \assert ⊦
" iabbrev \models ⊧
" iabbrev \vDash ⊨
" iabbrev \Vdash ⊩
" iabbrev \Vvdash ⊪
" iabbrev \VDash ⊫
" iabbrev \nvdash ⊬
" iabbrev \nvDash ⊭
" iabbrev \nVdash ⊮
" 
" iabbrev \nVDash ⊯
" iabbrev \prurel ⊰
" iabbrev \scurel ⊱
" iabbrev \vartriangleleft ⊲
" iabbrev \vartriangleright ⊳
" iabbrev \trianglelefteq ⊴
" iabbrev \trianglerighteq ⊵
" iabbrev \origof ⊶
" iabbrev \imageof ⊷
" iabbrev \multimap ⊸
" iabbrev \bowtie ⋈
" iabbrev \backsimeq ⋍
" iabbrev \Subset ⋐
" iabbrev \Supset ⋑
" iabbrev \pitchfork ⋔
" iabbrev \equalparallel ⋕
" iabbrev \lessdot ⋖
" iabbrev \gtrdot ⋗
" iabbrev \lll ⋘
" iabbrev \ggg ⋙
" iabbrev \lesseqgtr ⋚
" iabbrev \gtreqless ⋛
" iabbrev \eqless ⋜
" iabbrev \eqgtr ⋝
" iabbrev \curlyeqprec ⋞
" iabbrev \curlyeqsucc ⋟
" iabbrev \npreccurlyeq ⋠
" iabbrev \nsucccurlyeq ⋡
" iabbrev \nsqsubseteq ⋢
" iabbrev \nsqsupseteq ⋣
" iabbrev \sqsubsetneq ⋤
" iabbrev \sqsupsetneq ⋥
" iabbrev \lnsim ⋦
" iabbrev \gnsim ⋧
" iabbrev \precnsim ⋨
" iabbrev \succnsim ⋩
" iabbrev \nvartriangleleft ⋪
" iabbrev \nvartriangleright ⋫
" iabbrev \ntrianglelefteq ⋬
" iabbrev \ntrianglerighteq ⋭
" iabbrev \vdots ⋮
" iabbrev \adots ⋰
" iabbrev \ddots ⋱
" iabbrev \disin ⋲
" iabbrev \varisins ⋳
" iabbrev \isins ⋴
" iabbrev \isindot ⋵
" iabbrev \varisinobar ⋶
" iabbrev \isinobar ⋷
" iabbrev \isinvb ⋸
" 
" iabbrev \isinE ⋹
" iabbrev \nisd ⋺
" iabbrev \varnis ⋻
" iabbrev \nis ⋼
" iabbrev \varniobar ⋽
" iabbrev \niobar ⋾
" iabbrev \bagmember ⋿
" iabbrev \frown ⌢
" iabbrev \smile ⌣
" iabbrev \APLnotslash ⌿
" iabbrev \vartriangle ▵
" iabbrev \perp ⟂
" iabbrev \bsolhsub ⟈
" iabbrev \suphsol ⟉
" iabbrev \upin ⟒
" iabbrev \pullback ⟓
" iabbrev \pushout ⟔
" iabbrev \DashVDash ⟚
" iabbrev \dashVdash ⟛
" iabbrev \multimapinv ⟜
" iabbrev \vlongdash ⟝
" iabbrev \longdashv ⟞
" iabbrev \cirbot ⟟
" iabbrev \UUparrow ⟰
" iabbrev \DDownarrow ⟱
" iabbrev \acwgapcirclearrow ⟲
" iabbrev \cwgapcirclearrow ⟳
" iabbrev \rightarrowonoplus ⟴
" iabbrev \longleftarrow ⟵
" iabbrev \longrightarrow ⟶
" iabbrev \longleftrightarrow ⟷
" iabbrev \Longleftarrow ⟸
" iabbrev \Longrightarrow ⟹
" iabbrev \Longleftrightarrow ⟺
" iabbrev \longmapsfrom ⟻
" iabbrev \longmapsto ⟼
" iabbrev \Longmapsfrom ⟽
" iabbrev \Longmapsto ⟾
" iabbrev \longrightsquigarrow ⟿
" iabbrev \nvtwoheadrightarrow ⤀
" iabbrev \nVtwoheadrightarrow ⤁
" iabbrev \nvLeftarrow ⤂
" iabbrev \nvRightarrow ⤃
" iabbrev \nvLeftrightarrow ⤄
" iabbrev \twoheadmapsto ⤅
" iabbrev \Mapsfrom ⤆
" iabbrev \Mapsto ⤇
" iabbrev \downarrowbarred ⤈
" iabbrev \uparrowbarred ⤉
" 
" iabbrev \Uuparrow ⤊
" iabbrev \Ddownarrow ⤋
" iabbrev \leftbkarrow ⤌
" iabbrev \rightbkarrow ⤍
" iabbrev \leftdbkarrow ⤎
" iabbrev \dbkarow ⤏
" iabbrev \drbkarow ⤐
" iabbrev \rightdotarrow ⤑
" iabbrev \baruparrow ⤒
" iabbrev \downarrowbar ⤓
" iabbrev \nvrightarrowtail ⤔
" iabbrev \nVrightarrowtail ⤕
" iabbrev \twoheadrightarrowtail ⤖
" iabbrev \nvtwoheadrightarrowtail ⤗
" iabbrev \nVtwoheadrightarrowtail ⤘
" iabbrev \lefttail ⤙
" iabbrev \righttail ⤚
" iabbrev \leftdbltail ⤛
" iabbrev \rightdbltail ⤜
" iabbrev \diamondleftarrow ⤝
" iabbrev \rightarrowdiamond ⤞
" iabbrev \diamondleftarrowbar ⤟
" iabbrev \barrightarrowdiamond ⤠
" iabbrev \nwsearrow ⤡
" iabbrev \neswarrow ⤢
" iabbrev \hknwarrow ⤣
" iabbrev \hknearrow ⤤
" iabbrev \hksearow ⤥
" iabbrev \hkswarow ⤦
" iabbrev \tona ⤧
" iabbrev \toea ⤨
" iabbrev \tosa ⤩
" iabbrev \towa ⤪
" iabbrev \rightcurvedarrow ⤳
" iabbrev \leftdowncurvedarrow ⤶
" iabbrev \rightdowncurvedarrow ⤷
" iabbrev \cwrightarcarrow ⤸
" iabbrev \acwleftarcarrow ⤹
" iabbrev \acwoverarcarrow ⤺
" iabbrev \acwunderarcarrow ⤻
" iabbrev \curvearrowrightminus ⤼
" iabbrev \curvearrowleftplus ⤽
" iabbrev \cwundercurvearrow ⤾
" iabbrev \ccwundercurvearrow ⤿
" iabbrev \acwcirclearrow ⥀
" iabbrev \cwcirclearrow ⥁
" iabbrev \rightarrowshortleftarrow ⥂
" iabbrev \leftarrowshortrightarrow ⥃
" iabbrev \shortrightarrowleftarrow ⥄
" 
" iabbrev \rightarrowplus ⥅
" iabbrev \leftarrowplus ⥆
" iabbrev \rightarrowx ⥇
" iabbrev \leftrightarrowcircle ⥈
" iabbrev \twoheaduparrowcircle ⥉
" iabbrev \leftrightharpoonupdown ⥊
" iabbrev \leftrightharpoondownup ⥋
" iabbrev \updownharpoonrightleft ⥌
" iabbrev \updownharpoonleftright ⥍
" iabbrev \leftrightharpoonupup ⥎
" iabbrev \updownharpoonrightright ⥏
" iabbrev \leftrightharpoondowndown ⥐
" iabbrev \updownharpoonleftleft ⥑
" iabbrev \barleftharpoonup ⥒
" iabbrev \rightharpoonupbar ⥓
" iabbrev \barupharpoonright ⥔
" iabbrev \downharpoonrightbar ⥕
" iabbrev \barleftharpoondown ⥖
" iabbrev \rightharpoondownbar ⥗
" iabbrev \barupharpoonleft ⥘
" iabbrev \downharpoonleftbar ⥙
" iabbrev \leftharpoonupbar ⥚
" iabbrev \barrightharpoonup ⥛
" iabbrev \upharpoonrightbar ⥜
" iabbrev \bardownharpoonright ⥝
" iabbrev \leftharpoondownbar ⥞
" iabbrev \barrightharpoondown ⥟
" iabbrev \upharpoonleftbar ⥠
" iabbrev \bardownharpoonleft ⥡
" iabbrev \leftharpoonsupdown ⥢
" iabbrev \upharpoonsleftright ⥣
" iabbrev \rightharpoonsupdown ⥤
" iabbrev \downharpoonsleftright ⥥
" iabbrev \leftrightharpoonsup ⥦
" iabbrev \leftrightharpoonsdown ⥧
" iabbrev \rightleftharpoonsup ⥨
" iabbrev \rightleftharpoonsdown ⥩
" iabbrev \leftharpoonupdash ⥪
" iabbrev \dashleftharpoondown ⥫
" iabbrev \rightharpoonupdash ⥬
" iabbrev \dashrightharpoondown ⥭
" iabbrev \updownharpoonsleftright ⥮
" iabbrev \downupharpoonsleftright ⥯
" iabbrev \rightimply ⥰
" iabbrev \equalrightarrow ⥱
" 
" iabbrev \similarrightarrow ⥲
" iabbrev \leftarrowsimilar ⥳
" iabbrev \rightarrowsimilar ⥴
" iabbrev \rightarrowapprox ⥵
" iabbrev \ltlarr ⥶
" iabbrev \leftarrowless ⥷
" iabbrev \gtrarr ⥸
" iabbrev \subrarr ⥹
" iabbrev \leftarrowsubset ⥺
" iabbrev \suplarr ⥻
" iabbrev \leftfishtail ⥼
" iabbrev \rightfishtail ⥽
" iabbrev \upfishtail ⥾
" iabbrev \downfishtail ⥿
" iabbrev \rtriltri ⧎
" iabbrev \ltrivb ⧏
" iabbrev \vbrtri ⧐
" iabbrev \lfbowtie ⧑
" iabbrev \rfbowtie ⧒
" iabbrev \fbowtie ⧓
" iabbrev \lftimes ⧔
" iabbrev \rftimes ⧕
" iabbrev \dualmap ⧟
" iabbrev \lrtriangleeq ⧡
" iabbrev \eparsl ⧣
" iabbrev \smeparsl ⧤
" iabbrev \eqvparsl ⧥
" iabbrev \gleichstark ⧦
" iabbrev \ruledelayed ⧴
" iabbrev \veeonwedge ⩙
" iabbrev \eqdot ⩦
" iabbrev \dotequiv ⩧
" iabbrev \equivVert ⩨
" iabbrev \equivVvert ⩩
" iabbrev \dotsim ⩪
" iabbrev \simrdots ⩫
" iabbrev \simminussim ⩬
" iabbrev \congdot ⩭
" iabbrev \asteq ⩮
" iabbrev \hatapprox ⩯
" iabbrev \approxeqq ⩰
" iabbrev \eqqsim ⩳
" iabbrev \Coloneq ⩴
" iabbrev \eqeq ⩵
" iabbrev \eqeqeq ⩶
" iabbrev \ddotseq ⩷
" iabbrev \equivDD ⩸
" iabbrev \ltcir ⩹
" iabbrev \gtcir ⩺
" iabbrev \ltquest ⩻
" 
" iabbrev \gtquest ⩼
" iabbrev \leqslant ⩽
" iabbrev \geqslant ⩾
" iabbrev \lesdot ⩿
" iabbrev \gesdot ⪀
" iabbrev \lesdoto ⪁
" iabbrev \gesdoto ⪂
" iabbrev \lesdotor ⪃
" iabbrev \gesdotol ⪄
" iabbrev \lessapprox ⪅
" iabbrev \gtrapprox ⪆
" iabbrev \lneq ⪇
" iabbrev \gneq ⪈
" iabbrev \lnapprox ⪉
" iabbrev \gnapprox ⪊
" iabbrev \lesseqqgtr ⪋
" iabbrev \gtreqqless ⪌
" iabbrev \lsime ⪍
" iabbrev \gsime ⪎
" iabbrev \lsimg ⪏
" iabbrev \gsiml ⪐
" iabbrev \lgE ⪑
" iabbrev \glE ⪒
" iabbrev \lesges ⪓
" iabbrev \gesles ⪔
" iabbrev \eqslantless ⪕
" iabbrev \eqslantgtr ⪖
" iabbrev \elsdot ⪗
" iabbrev \egsdot ⪘
" iabbrev \eqqless ⪙
" iabbrev \eqqgtr ⪚
" iabbrev \eqqslantless ⪛
" iabbrev \eqqslantgtr ⪜
" iabbrev \simless ⪝
" iabbrev \simgtr ⪞
" iabbrev \simlE ⪟
" iabbrev \simgE ⪠
" iabbrev \Lt ⪡
" iabbrev \Gt ⪢
" iabbrev \partialmeetcontraction ⪣
" iabbrev \glj ⪤
" iabbrev \gla ⪥
" iabbrev \ltcc ⪦
" iabbrev \gtcc ⪧
" iabbrev \lescc ⪨
" iabbrev \gescc ⪩
" iabbrev \smt ⪪
" iabbrev \lat ⪫
" 
" iabbrev \smte ⪬
" iabbrev \late ⪭
" iabbrev \bumpeqq ⪮
" iabbrev \preceq ⪯
" iabbrev \succeq ⪰
" iabbrev \precneq ⪱
" iabbrev \succneq ⪲
" iabbrev \preceqq ⪳
" iabbrev \succeqq ⪴
" iabbrev \precneqq ⪵
" iabbrev \succneqq ⪶
" iabbrev \precapprox ⪷
" iabbrev \succapprox ⪸
" iabbrev \precnapprox ⪹
" iabbrev \succnapprox ⪺
" iabbrev \Prec ⪻
" iabbrev \Succ ⪼
" iabbrev \subsetdot ⪽
" iabbrev \supsetdot ⪾
" iabbrev \subsetplus ⪿
" iabbrev \supsetplus ⫀
" iabbrev \submult ⫁
" iabbrev \supmult ⫂
" iabbrev \subedot ⫃
" iabbrev \supedot ⫄
" iabbrev \subseteqq ⫅
" iabbrev \supseteqq ⫆
" iabbrev \subsim ⫇
" iabbrev \supsim ⫈
" iabbrev \subsetapprox ⫉
" iabbrev \supsetapprox ⫊
" iabbrev \subsetneqq ⫋
" iabbrev \supsetneqq ⫌
" iabbrev \lsqhook ⫍
" iabbrev \rsqhook ⫎
" iabbrev \csub ⫏
" iabbrev \csup ⫐
" iabbrev \csube ⫑
" iabbrev \csupe ⫒
" iabbrev \subsup ⫓
" iabbrev \supsub ⫔
" iabbrev \subsub ⫕
" iabbrev \supsup ⫖
" iabbrev \suphsub ⫗
" iabbrev \supdsub ⫘
" iabbrev \forkv ⫙
" iabbrev \topfork ⫚
" iabbrev \mlcp ⫛
" iabbrev \forks ⫝̸
" iabbrev \forksnot ⫝
" 
" iabbrev \shortlefttack ⫞
" iabbrev \shortdowntack ⫟
" iabbrev \shortuptack ⫠
" iabbrev \vDdash ⫢
" iabbrev \dashV ⫣
" iabbrev \Dashv ⫤
" iabbrev \DashV ⫥
" iabbrev \varVdash ⫦
" iabbrev \Barv ⫧
" iabbrev \vBar ⫨
" iabbrev \vBarv ⫩
" iabbrev \barV ⫪
" iabbrev \Vbar ⫫
" iabbrev \Not ⫬
" iabbrev \bNot ⫭
" iabbrev \revnmid ⫮
" iabbrev \cirmid ⫯
" iabbrev \midcir ⫰
" iabbrev \nhpar ⫲
" iabbrev \parsim ⫳
" iabbrev \lllnest ⫷
" iabbrev \gggnest ⫸
" iabbrev \leqqslant ⫹
" iabbrev \geqqslant ⫺
" iabbrev \circleonleftarrow ⬰
" iabbrev \leftthreearrows ⬱
" iabbrev \leftarrowonoplus ⬲
" iabbrev \longleftsquigarrow ⬳
" iabbrev \nvtwoheadleftarrow ⬴
" iabbrev \nVtwoheadleftarrow ⬵
" iabbrev \twoheadmapsfrom ⬶
" iabbrev \twoheadleftdbkarrow ⬷
" iabbrev \leftdotarrow ⬸
" iabbrev \nvleftarrowtail ⬹
" iabbrev \nVleftarrowtail ⬺
" iabbrev \twoheadleftarrowtail ⬻
" iabbrev \nvtwoheadleftarrowtail ⬼
" iabbrev \nVtwoheadleftarrowtail ⬽
" iabbrev \leftarrowx ⬾
" iabbrev \leftcurvedarrow ⬿
" iabbrev \equalleftarrow ⭀
" iabbrev \bsimilarleftarrow ⭁
" iabbrev \leftarrowbackapprox ⭂
" iabbrev \rightarrowgtr ⭃
" iabbrev \rightarrowsupset ⭄
" iabbrev \LLeftarrow ⭅
" iabbrev \RRightarrow ⭆
" iabbrev \bsimilarrightarrow ⭇
" iabbrev \rightarrowbackapprox ⭈
" 
" iabbrev \similarleftarrow ⭉
" iabbrev \leftarrowapprox ⭊
" iabbrev \leftarrowbsimilar ⭋
" iabbrev \rightarrowbsimilar ⭌
" 
" iabbrev \mbfA 𝐀
" iabbrev \mbfB 𝐁
" iabbrev \mbfC 𝐂
" iabbrev \mbfD 𝐃
" iabbrev \mbfE 𝐄
" iabbrev \mbfF 𝐅
" iabbrev \mbfG 𝐆
" iabbrev \mbfH 𝐇
" iabbrev \mbfI 𝐈
" iabbrev \mbfJ 𝐉
" iabbrev \mbfK 𝐊
" iabbrev \mbfL 𝐋
" iabbrev \mbfM 𝐌
" iabbrev \mbfN 𝐍
" iabbrev \mbfO 𝐎
" iabbrev \mbfP 𝐏
" iabbrev \mbfQ 𝐐
" iabbrev \mbfR 𝐑
" iabbrev \mbfS 𝐒
" iabbrev \mbfT 𝐓
" iabbrev \mbfU 𝐔
" iabbrev \mbfV 𝐕
" iabbrev \mbfW 𝐖
" iabbrev \mbfX 𝐗
" iabbrev \mbfY 𝐘
" iabbrev \mbfZ 𝐙
" iabbrev \mbfa 𝐚
" iabbrev \mbfb 𝐛
" iabbrev \mbfc 𝐜
" iabbrev \mbfd 𝐝
" iabbrev \mbfe 𝐞
" iabbrev \mbff 𝐟
" iabbrev \mbfg 𝐠
" iabbrev \mbfh 𝐡
" iabbrev \mbfi 𝐢
" iabbrev \mbfj 𝐣
" iabbrev \mbfk 𝐤
" iabbrev \mbfl 𝐥
" iabbrev \mbfm 𝐦
" iabbrev \mbfn 𝐧
" iabbrev \mbfo 𝐨
" iabbrev \mbfp 𝐩
" iabbrev \mbfq 𝐪
" iabbrev \mbfr 𝐫
" iabbrev \mbfs 𝐬
" iabbrev \mbft 𝐭
" iabbrev \mbfu 𝐮
" iabbrev \mbfv 𝐯
" iabbrev \mbfw 𝐰
" iabbrev \mbfx 𝐱
" iabbrev \mbfy 𝐲
" iabbrev \mbfz 𝐳
" 
" iabbrev \mitA 𝐴
" iabbrev \mitB 𝐵
" iabbrev \mitC 𝐶
" iabbrev \mitD 𝐷
" iabbrev \mitE 𝐸
" iabbrev \mitF 𝐹
" iabbrev \mitG 𝐺
" iabbrev \mitH 𝐻
" iabbrev \mitI 𝐼
" iabbrev \mitJ 𝐽
" iabbrev \mitK 𝐾
" iabbrev \mitL 𝐿
" iabbrev \mitM 𝑀
" iabbrev \mitN 𝑁
" iabbrev \mitO 𝑂
" iabbrev \mitP 𝑃
" iabbrev \mitQ 𝑄
" iabbrev \mitR 𝑅
" iabbrev \mitS 𝑆
" iabbrev \mitT 𝑇
" iabbrev \mitU 𝑈
" iabbrev \mitV 𝑉
" iabbrev \mitW 𝑊
" iabbrev \mitX 𝑋
" iabbrev \mitY 𝑌
" iabbrev \mitZ 𝑍
" iabbrev \mita 𝑎
" iabbrev \mitb 𝑏
" iabbrev \mitc 𝑐
" iabbrev \mitd 𝑑
" iabbrev \mite 𝑒
" iabbrev \mitf 𝑓
" iabbrev \mitg 𝑔
" iabbrev \miti 𝑖
" iabbrev \mitj 𝑗
" iabbrev \mitk 𝑘
" iabbrev \mitl 𝑙
" iabbrev \mitm 𝑚
" iabbrev \mitn 𝑛
" iabbrev \mito 𝑜
" iabbrev \mitp 𝑝
" iabbrev \mitq 𝑞
" iabbrev \mitr 𝑟
" iabbrev \mits 𝑠
" iabbrev \mitt 𝑡
" iabbrev \mitu 𝑢
" iabbrev \mitv 𝑣
" iabbrev \mitw 𝑤
" iabbrev \mitx 𝑥
" iabbrev \mity 𝑦
" iabbrev \mitz 𝑧
" iabbrev \imath 𝚤
" iabbrev \jmath 𝚥
" 
" iabbrev \mbfitA 𝑨
" iabbrev \mbfitB 𝑩
" iabbrev \mbfitC 𝑪
" iabbrev \mbfitD 𝑫
" iabbrev \mbfitE 𝑬
" iabbrev \mbfitF 𝑭
" iabbrev \mbfitG 𝑮
" iabbrev \mbfitH 𝑯
" iabbrev \mbfitI 𝑰
" iabbrev \mbfitJ 𝑱
" iabbrev \mbfitK 𝑲
" iabbrev \mbfitL 𝑳
" iabbrev \mbfitM 𝑴
" iabbrev \mbfitN 𝑵
" iabbrev \mbfitO 𝑶
" iabbrev \mbfitP 𝑷
" iabbrev \mbfitQ 𝑸
" iabbrev \mbfitR 𝑹
" iabbrev \mbfitS 𝑺
" iabbrev \mbfitT 𝑻
" iabbrev \mbfitU 𝑼
" iabbrev \mbfitV 𝑽
" iabbrev \mbfitW 𝑾
" iabbrev \mbfitX 𝑿
" iabbrev \mbfitY 𝒀
" iabbrev \mbfitZ 𝒁
" iabbrev \mbfita 𝒂
" iabbrev \mbfitb 𝒃
" iabbrev \mbfitc 𝒄
" iabbrev \mbfitd 𝒅
" iabbrev \mbfite 𝒆
" iabbrev \mbfitf 𝒇
" iabbrev \mbfitg 𝒈
" iabbrev \mbfith 𝒉
" iabbrev \mbfiti 𝒊
" iabbrev \mbfitj 𝒋
" iabbrev \mbfitk 𝒌
" iabbrev \mbfitl 𝒍
" iabbrev \mbfitm 𝒎
" iabbrev \mbfitn 𝒏
" iabbrev \mbfito 𝒐
" iabbrev \mbfitp 𝒑
" iabbrev \mbfitq 𝒒
" iabbrev \mbfitr 𝒓
" iabbrev \mbfits 𝒔
" iabbrev \mbfitt 𝒕
" iabbrev \mbfitu 𝒖
" iabbrev \mbfitv 𝒗
" iabbrev \mbfitw 𝒘
" iabbrev \mbfitx 𝒙
" iabbrev \mbfity 𝒚
" iabbrev \mbfitz 𝒛
" 
" iabbrev \mscrA 𝒜
" iabbrev \mscrB ℬ
" iabbrev \mscrC 𝒞
" iabbrev \mscrD 𝒟
" iabbrev \mscrE ℰ
" iabbrev \mscrF ℱ
" iabbrev \mscrG 𝒢
" iabbrev \mscrH ℋ
" iabbrev \mscrI ℐ
" iabbrev \mscrJ 𝒥
" iabbrev \mscrK 𝒦
" iabbrev \mscrL ℒ
" iabbrev \mscrM ℳ
" iabbrev \mscrN 𝒩
" iabbrev \mscrO 𝒪
" iabbrev \mscrP 𝒫
" iabbrev \mscrQ 𝒬
" iabbrev \mscrR ℛ
" iabbrev \mscrS 𝒮
" iabbrev \mscrT 𝒯
" iabbrev \mscrU 𝒰
" iabbrev \mscrV 𝒱
" iabbrev \mscrW 𝒲
" iabbrev \mscrX 𝒳
" iabbrev \mscrY 𝒴
" iabbrev \mscrZ 𝒵
" iabbrev \mscra 𝒶
" iabbrev \mscrb 𝒷
" iabbrev \mscrc 𝒸
" iabbrev \mscrd 𝒹
" iabbrev \mscre ℯ
" iabbrev \mscrf 𝒻
" iabbrev \mscrg ℊ
" iabbrev \mscrh 𝒽
" iabbrev \mscri 𝒾
" iabbrev \mscrj 𝒿
" iabbrev \mscrk 𝓀
" iabbrev \mscrl 𝓁
" iabbrev \mscrm 𝓂
" iabbrev \mscrn 𝓃
" iabbrev \mscro ℴ
" iabbrev \mscrp 𝓅
" iabbrev \mscrq 𝓆
" iabbrev \mscrr 𝓇
" iabbrev \mscrs 𝓈
" iabbrev \mscrt 𝓉
" iabbrev \mscru 𝓊
" iabbrev \mscrv 𝓋
" iabbrev \mscrw 𝓌
" iabbrev \mscrx 𝓍
" iabbrev \mscry 𝓎
" iabbrev \mscrz 𝓏
" 
" iabbrev \mbfscrA 𝓐
" iabbrev \mbfscrB 𝓑
" iabbrev \mbfscrC 𝓒
" iabbrev \mbfscrD 𝓓
" iabbrev \mbfscrE 𝓔
" iabbrev \mbfscrF 𝓕
" iabbrev \mbfscrG 𝓖
" iabbrev \mbfscrH 𝓗
" iabbrev \mbfscrI 𝓘
" iabbrev \mbfscrJ 𝓙
" iabbrev \mbfscrK 𝓚
" iabbrev \mbfscrL 𝓛
" iabbrev \mbfscrM 𝓜
" iabbrev \mbfscrN 𝓝
" iabbrev \mbfscrO 𝓞
" iabbrev \mbfscrP 𝓟
" iabbrev \mbfscrQ 𝓠
" iabbrev \mbfscrR 𝓡
" iabbrev \mbfscrS 𝓢
" iabbrev \mbfscrT 𝓣
" iabbrev \mbfscrU 𝓤
" iabbrev \mbfscrV 𝓥
" iabbrev \mbfscrW 𝓦
" iabbrev \mbfscrX 𝓧
" iabbrev \mbfscrY 𝓨
" iabbrev \mbfscrZ 𝓩
" iabbrev \mbfscra 𝓪
" iabbrev \mbfscrb 𝓫
" iabbrev \mbfscrc 𝓬
" iabbrev \mbfscrd 𝓭
" iabbrev \mbfscre 𝓮
" iabbrev \mbfscrf 𝓯
" iabbrev \mbfscrg 𝓰
" iabbrev \mbfscrh 𝓱
" iabbrev \mbfscri 𝓲
" iabbrev \mbfscrj 𝓳
" iabbrev \mbfscrk 𝓴
" iabbrev \mbfscrl 𝓵
" iabbrev \mbfscrm 𝓶
" iabbrev \mbfscrn 𝓷
" iabbrev \mbfscro 𝓸
" iabbrev \mbfscrp 𝓹
" iabbrev \mbfscrq 𝓺
" iabbrev \mbfscrr 𝓻
" iabbrev \mbfscrs 𝓼
" iabbrev \mbfscrt 𝓽
" iabbrev \mbfscru 𝓾
" iabbrev \mbfscrv 𝓿
" iabbrev \mbfscrw 𝔀
" iabbrev \mbfscrx 𝔁
" iabbrev \mbfscry 𝔂
" iabbrev \mbfscrz 𝔃
" iabbrev \mfrakA 𝔄
" iabbrev \mfrakB 𝔅
" iabbrev \mfrakC ℭ
" iabbrev \mfrakD 𝔇
" iabbrev \mfrakE 𝔈
" iabbrev \mfrakF 𝔉
" iabbrev \mfrakG 𝔊	
" iabbrev \mfrakJ 𝔍
" iabbrev \mfrakK 𝔎
" iabbrev \mfrakL 𝔏
" iabbrev \mfrakM 𝔐
" iabbrev \mfrakN 𝔑
" iabbrev \mfrakO 𝔒
" iabbrev \mfrakP 𝔓
" iabbrev \mfrakQ 𝔔	
" iabbrev \mfrakS 𝔖
" iabbrev \mfrakT 𝔗
" iabbrev \mfrakU 𝔘
" iabbrev \mfrakV 𝔙
" iabbrev \mfrakW 𝔚
" iabbrev \mfrakX 𝔛
" iabbrev \mfrakY 𝔜
" iabbrev \mfraka 𝔞
" iabbrev \mfrakb 𝔟
" iabbrev \mfrakc 𝔠
" iabbrev \mfrakd 𝔡
" iabbrev \mfrake 𝔢
" iabbrev \mfrakf 𝔣
" iabbrev \mfrakg 𝔤
" iabbrev \mfrakh 𝔥
" iabbrev \mfraki 𝔦
" iabbrev \mfrakj 𝔧
" iabbrev \mfrakk 𝔨
" iabbrev \mfrakl 𝔩
" iabbrev \mfrakm 𝔪
" iabbrev \mfrakn 𝔫
" iabbrev \mfrako 𝔬
" iabbrev \mfrakp 𝔭
" iabbrev \mfrakq 𝔮
" iabbrev \mfrakr 𝔯
" iabbrev \mfraks 𝔰
" iabbrev \mfrakt 𝔱
" iabbrev \mfraku 𝔲
" iabbrev \mfrakv 𝔳
" iabbrev \mfrakw 𝔴
" iabbrev \mfrakx 𝔵
" iabbrev \mfraky 𝔶
" iabbrev \mfrakz 𝔷
" 
" iabbrev \BbbA 𝔸
" iabbrev \BbbB 𝔹
" iabbrev \BbbC ℂ
" iabbrev \BbbD 𝔻
" iabbrev \BbbE 𝔼
" iabbrev \BbbF 𝔽
" iabbrev \BbbG 𝔾
" iabbrev \BbbH ℍ
" iabbrev \BbbI 𝕀
" iabbrev \BbbJ 𝕁
" iabbrev \BbbK 𝕂
" iabbrev \BbbL 𝕃
" iabbrev \BbbM 𝕄
" iabbrev \BbbN ℕ
" iabbrev \BbbO 𝕆
" iabbrev \BbbP ℙ
" iabbrev \BbbQ ℚ
" iabbrev \BbbR ℝ
" iabbrev \BbbS 𝕊
" iabbrev \BbbT 𝕋
" iabbrev \BbbU 𝕌
" iabbrev \BbbV 𝕍
" iabbrev \BbbW 𝕎
" iabbrev \BbbX 𝕏
" iabbrev \BbbY 𝕐
" iabbrev \BbbZ ℤ
" iabbrev \Bbba 𝕒
" iabbrev \Bbbb 𝕓
" iabbrev \Bbbc 𝕔
" iabbrev \Bbbd 𝕕
" iabbrev \Bbbe 𝕖
" iabbrev \Bbbf 𝕗
" iabbrev \Bbbg 𝕘
" iabbrev \Bbbh 𝕙
" iabbrev \Bbbi 𝕚
" iabbrev \Bbbj 𝕛
" iabbrev \Bbbk 𝕜
" iabbrev \Bbbl 𝕝
" iabbrev \Bbbm 𝕞
" iabbrev \Bbbn 𝕟
" iabbrev \Bbbo 𝕠
" iabbrev \Bbbp 𝕡
" iabbrev \Bbbq 𝕢
" iabbrev \Bbbr 𝕣
" iabbrev \Bbbs 𝕤
" iabbrev \Bbbt 𝕥
" iabbrev \Bbbu 𝕦
" iabbrev \Bbbv 𝕧
" iabbrev \Bbbw 𝕨
" iabbrev \Bbbx 𝕩
" iabbrev \Bbby 𝕪
" iabbrev \Bbbz 𝕫
" 
" iabbrev \mbffrakA 𝕬
" iabbrev \mbffrakB 𝕭
" iabbrev \mbffrakC 𝕮
" iabbrev \mbffrakD 𝕯
" iabbrev \mbffrakE 𝕰
" iabbrev \mbffrakF 𝕱
" iabbrev \mbffrakG 𝕲
" iabbrev \mbffrakH 𝕳
" iabbrev \mbffrakI 𝕴
" iabbrev \mbffrakJ 𝕵
" iabbrev \mbffrakK 𝕶
" iabbrev \mbffrakL 𝕷
" iabbrev \mbffrakM 𝕸
" iabbrev \mbffrakN 𝕹
" iabbrev \mbffrakO 𝕺
" iabbrev \mbffrakP 𝕻
" iabbrev \mbffrakQ 𝕼
" iabbrev \mbffrakR 𝕽
" iabbrev \mbffrakS 𝕾
" iabbrev \mbffrakT 𝕿
" iabbrev \mbffrakU 𝖀
" iabbrev \mbffrakV 𝖁
" iabbrev \mbffrakW 𝖂
" iabbrev \mbffrakX 𝖃
" iabbrev \mbffrakY 𝖄
" iabbrev \mbffrakZ 𝖅
" iabbrev \mbffraka 𝖆
" iabbrev \mbffrakb 𝖇
" iabbrev \mbffrakc 𝖈
" iabbrev \mbffrakd 𝖉
" iabbrev \mbffrake 𝖊
" iabbrev \mbffrakf 𝖋
" iabbrev \mbffrakg 𝖌
" iabbrev \mbffrakh 𝖍
" iabbrev \mbffraki 𝖎
" iabbrev \mbffrakj 𝖏
" iabbrev \mbffrakk 𝖐
" iabbrev \mbffrakl 𝖑
" iabbrev \mbffrakm 𝖒
" iabbrev \mbffrakn 𝖓
" iabbrev \mbffrako 𝖔
" iabbrev \mbffrakp 𝖕
" iabbrev \mbffrakq 𝖖
" iabbrev \mbffrakr 𝖗
" iabbrev \mbffraks 𝖘
" iabbrev \mbffrakt 𝖙
" iabbrev \mbffraku 𝖚
" iabbrev \mbffrakv 𝖛
" iabbrev \mbffrakw 𝖜
" iabbrev \mbffrakx 𝖝
" iabbrev \mbffraky 𝖞
" iabbrev \mbffrakz 𝖟
" 
" iabbrev \msansA 𝖠
" iabbrev \msansB 𝖡
" iabbrev \msansC 𝖢
" iabbrev \msansD 𝖣
" iabbrev \msansE 𝖤
" iabbrev \msansF 𝖥
" iabbrev \msansG 𝖦
" iabbrev \msansH 𝖧
" iabbrev \msansI 𝖨
" iabbrev \msansJ 𝖩
" iabbrev \msansK 𝖪
" iabbrev \msansL 𝖫
" iabbrev \msansM 𝖬
" iabbrev \msansN 𝖭
" iabbrev \msansO 𝖮
" iabbrev \msansP 𝖯
" iabbrev \msansQ 𝖰
" iabbrev \msansR 𝖱
" iabbrev \msansS 𝖲
" iabbrev \msansT 𝖳
" iabbrev \msansU 𝖴
" iabbrev \msansV 𝖵
" iabbrev \msansW 𝖶
" iabbrev \msansX 𝖷
" iabbrev \msansY 𝖸
" iabbrev \msansZ 𝖹
" iabbrev \msansa 𝖺
" iabbrev \msansb 𝖻
" iabbrev \msansc 𝖼
" iabbrev \msansd 𝖽
" iabbrev \msanse 𝖾
" iabbrev \msansf 𝖿
" iabbrev \msansg 𝗀
" iabbrev \msansh 𝗁
" iabbrev \msansi 𝗂
" iabbrev \msansj 𝗃
" iabbrev \msansk 𝗄
" iabbrev \msansl 𝗅
" iabbrev \msansm 𝗆
" iabbrev \msansn 𝗇
" iabbrev \msanso 𝗈
" iabbrev \msansp 𝗉
" iabbrev \msansq 𝗊
" iabbrev \msansr 𝗋
" iabbrev \msanss 𝗌
" iabbrev \msanst 𝗍
" iabbrev \msansu 𝗎
" iabbrev \msansv 𝗏
" iabbrev \msansw 𝗐
" iabbrev \msansx 𝗑
" iabbrev \msansy 𝗒
" iabbrev \msansz 𝗓
" 
" iabbrev \mbfsansA 𝗔
" iabbrev \mbfsansB 𝗕
" iabbrev \mbfsansC 𝗖
" iabbrev \mbfsansD 𝗗
" iabbrev \mbfsansE 𝗘
" iabbrev \mbfsansF 𝗙
" iabbrev \mbfsansG 𝗚
" iabbrev \mbfsansH 𝗛
" iabbrev \mbfsansI 𝗜
" iabbrev \mbfsansJ 𝗝
" iabbrev \mbfsansK 𝗞
" iabbrev \mbfsansL 𝗟
" iabbrev \mbfsansM 𝗠
" iabbrev \mbfsansN 𝗡
" iabbrev \mbfsansO 𝗢
" iabbrev \mbfsansP 𝗣
" iabbrev \mbfsansQ 𝗤
" iabbrev \mbfsansR 𝗥
" iabbrev \mbfsansS 𝗦
" iabbrev \mbfsansT 𝗧
" iabbrev \mbfsansU 𝗨
" iabbrev \mbfsansV 𝗩
" iabbrev \mbfsansW 𝗪
" iabbrev \mbfsansX 𝗫
" iabbrev \mbfsansY 𝗬
" iabbrev \mbfsansZ 𝗭
" iabbrev \mbfsansa 𝗮
" iabbrev \mbfsansb 𝗯
" iabbrev \mbfsansc 𝗰
" iabbrev \mbfsansd 𝗱
" iabbrev \mbfsanse 𝗲
" iabbrev \mbfsansf 𝗳
" iabbrev \mbfsansg 𝗴
" iabbrev \mbfsansh 𝗵
" iabbrev \mbfsansi 𝗶
" iabbrev \mbfsansj 𝗷
" iabbrev \mbfsansk 𝗸
" iabbrev \mbfsansl 𝗹
" iabbrev \mbfsansm 𝗺
" iabbrev \mbfsansn 𝗻
" iabbrev \mbfsanso 𝗼
" iabbrev \mbfsansp 𝗽
" iabbrev \mbfsansq 𝗾
" iabbrev \mbfsansr 𝗿
" iabbrev \mbfsanss 𝘀
" iabbrev \mbfsanst 𝘁
" iabbrev \mbfsansu 𝘂
" iabbrev \mbfsansv 𝘃
" iabbrev \mbfsansw 𝘄
" iabbrev \mbfsansx 𝘅
" iabbrev \mbfsansy 𝘆
" iabbrev \mbfsansz 𝘇
" 
" iabbrev \mitsansA 𝘈
" iabbrev \mitsansB 𝘉
" iabbrev \mitsansC 𝘊
" iabbrev \mitsansD 𝘋
" iabbrev \mitsansE 𝘌
" iabbrev \mitsansF 𝘍
" iabbrev \mitsansG 𝘎
" iabbrev \mitsansH 𝘏
" iabbrev \mitsansI 𝘐
" iabbrev \mitsansJ 𝘑
" iabbrev \mitsansK 𝘒
" iabbrev \mitsansL 𝘓
" iabbrev \mitsansM 𝘔
" iabbrev \mitsansN 𝘕
" iabbrev \mitsansO 𝘖
" iabbrev \mitsansP 𝘗
" iabbrev \mitsansQ 𝘘
" iabbrev \mitsansR 𝘙
" iabbrev \mitsansS 𝘚
" iabbrev \mitsansT 𝘛
" iabbrev \mitsansU 𝘜
" iabbrev \mitsansV 𝘝
" iabbrev \mitsansW 𝘞
" iabbrev \mitsansX 𝘟
" iabbrev \mitsansY 𝘠
" iabbrev \mitsansZ 𝘡
" iabbrev \mitsansa 𝘢
" iabbrev \mitsansb 𝘣
" iabbrev \mitsansc 𝘤
" iabbrev \mitsansd 𝘥
" iabbrev \mitsanse 𝘦
" iabbrev \mitsansf 𝘧
" iabbrev \mitsansg 𝘨
" iabbrev \mitsansh 𝘩
" iabbrev \mitsansi 𝘪
" iabbrev \mitsansj 𝘫
" iabbrev \mitsansk 𝘬
" iabbrev \mitsansl 𝘭
" iabbrev \mitsansm 𝘮
" iabbrev \mitsansn 𝘯
" iabbrev \mitsanso 𝘰
" iabbrev \mitsansp 𝘱
" iabbrev \mitsansq 𝘲
" iabbrev \mitsansr 𝘳
" iabbrev \mitsanss 𝘴
" iabbrev \mitsanst 𝘵
" iabbrev \mitsansu 𝘶
" iabbrev \mitsansv 𝘷
" iabbrev \mitsansw 𝘸
" iabbrev \mitsansx 𝘹
" iabbrev \mitsansy 𝘺
" iabbrev \mitsansz 𝘻
" 
" iabbrev \mbfitsansA 𝘼
" iabbrev \mbfitsansB 𝘽
" iabbrev \mbfitsansC 𝘾
" iabbrev \mbfitsansD 𝘿
" iabbrev \mbfitsansE 𝙀
" iabbrev \mbfitsansF 𝙁
" iabbrev \mbfitsansG 𝙂
" iabbrev \mbfitsansH 𝙃
" iabbrev \mbfitsansI 𝙄
" iabbrev \mbfitsansJ 𝙅
" iabbrev \mbfitsansK 𝙆
" iabbrev \mbfitsansL 𝙇
" iabbrev \mbfitsansM 𝙈
" iabbrev \mbfitsansN 𝙉
" iabbrev \mbfitsansO 𝙊
" iabbrev \mbfitsansP 𝙋
" iabbrev \mbfitsansQ 𝙌
" iabbrev \mbfitsansR 𝙍
" iabbrev \mbfitsansS 𝙎
" iabbrev \mbfitsansT 𝙏
" iabbrev \mbfitsansU 𝙐
" iabbrev \mbfitsansV 𝙑
" iabbrev \mbfitsansW 𝙒
" iabbrev \mbfitsansX 𝙓
" iabbrev \mbfitsansY 𝙔
" iabbrev \mbfitsansZ 𝙕
" iabbrev \mbfitsansa 𝙖
" iabbrev \mbfitsansb 𝙗
" iabbrev \mbfitsansc 𝙘
" iabbrev \mbfitsansd 𝙙
" iabbrev \mbfitsanse 𝙚
" iabbrev \mbfitsansf 𝙛
" iabbrev \mbfitsansg 𝙜
" iabbrev \mbfitsansh 𝙝
" iabbrev \mbfitsansi 𝙞
" iabbrev \mbfitsansj 𝙟
" iabbrev \mbfitsansk 𝙠
" iabbrev \mbfitsansl 𝙡
" iabbrev \mbfitsansm 𝙢
" iabbrev \mbfitsansn 𝙣
" iabbrev \mbfitsanso 𝙤
" iabbrev \mbfitsansp 𝙥
" iabbrev \mbfitsansq 𝙦
" iabbrev \mbfitsansr 𝙧
" iabbrev \mbfitsanss 𝙨
" iabbrev \mbfitsanst 𝙩
" iabbrev \mbfitsansu 𝙪
" iabbrev \mbfitsansv 𝙫
" iabbrev \mbfitsansw 𝙬
" iabbrev \mbfitsansx 𝙭
" iabbrev \mbfitsansy 𝙮
" iabbrev \mbfitsansz 𝙯
" 
" iabbrev \mttA 𝙰
" iabbrev \mttB 𝙱
" iabbrev \mttC 𝙲
" iabbrev \mttD 𝙳
" iabbrev \mttE 𝙴
" iabbrev \mttF 𝙵
" iabbrev \mttG 𝙶
" iabbrev \mttH 𝙷
" iabbrev \mttI 𝙸
" iabbrev \mttJ 𝙹
" iabbrev \mttK 𝙺
" iabbrev \mttL 𝙻
" iabbrev \mttM 𝙼
" iabbrev \mttN 𝙽
" iabbrev \mttO 𝙾
" iabbrev \mttP 𝙿
" iabbrev \mttQ 𝚀
" iabbrev \mttR 𝚁
" iabbrev \mttS 𝚂
" iabbrev \mttT 𝚃
" iabbrev \mttU 𝚄
" iabbrev \mttV 𝚅
" iabbrev \mttW 𝚆
" iabbrev \mttX 𝚇
" iabbrev \mttY 𝚈
" iabbrev \mttZ 𝚉
" iabbrev \mtta 𝚊
" iabbrev \mttb 𝚋
" iabbrev \mttc 𝚌
" iabbrev \mttd 𝚍
" iabbrev \mtte 𝚎
" iabbrev \mttf 𝚏
" iabbrev \mttg 𝚐
" iabbrev \mtth 𝚑
" iabbrev \mtti 𝚒
" iabbrev \mttj 𝚓
" iabbrev \mttk 𝚔
" iabbrev \mttl 𝚕
" iabbrev \mttm 𝚖
" iabbrev \mttn 𝚗
" iabbrev \mtto 𝚘
" iabbrev \mttp 𝚙
" iabbrev \mttq 𝚚
" iabbrev \mttr 𝚛
" iabbrev \mtts 𝚜
" iabbrev \mttt 𝚝
" iabbrev \mttu 𝚞
" iabbrev \mttv 𝚟
" iabbrev \mttw 𝚠
" iabbrev \mttx 𝚡
" iabbrev \mtty 𝚢
" iabbrev \mttz𝚣 𝚣
" 
" iabbrev \upAlpha Α
" iabbrev \upBeta Β
" iabbrev \upGamma Γ
" iabbrev \upDelta Δ
" iabbrev \upEpsilon Ε
" iabbrev \upZeta Ζ
" iabbrev \upEta Η
" iabbrev \upTheta Θ
" iabbrev \upIota Ι
" iabbrev \upKappa Κ
" iabbrev \upLambda Λ
" iabbrev \upMu Μ
" iabbrev \upNu Ν
" iabbrev \upXi Ξ
" iabbrev \upOmicron Ο
" iabbrev \upPi Π
" iabbrev \upRho Ρ
" iabbrev \upSigma Σ
" iabbrev \upTau Τ
" iabbrev \upUpsilon Υ
" iabbrev \upPhi Φ
" iabbrev \upChi Χ
" iabbrev \upPsi Ψ
" iabbrev \upOmega Ω
" iabbrev \nabla ∇
" iabbrev \upalpha α
" iabbrev \upbeta β
" iabbrev \upgamma γ
" iabbrev \updelta δ
" iabbrev \upepsilon ε
" iabbrev \upzeta ζ
" iabbrev \upeta η
" iabbrev \uptheta θ
" iabbrev \upiota ι
" iabbrev \upkappa κ
" iabbrev \uplambda λ
" iabbrev \upmu μ
" iabbrev \upnu ν
" iabbrev \upxi ξ
" iabbrev \upomicron ο
" iabbrev \uppi π
" iabbrev \uprho ρ
" iabbrev \upvarsigma ς
" iabbrev \upsigma σ
" iabbrev \uptau τ
" iabbrev \upupsilon υ
" iabbrev \upvarphi φ
" iabbrev \upchi χ
" iabbrev \uppsi ψ
" iabbrev \upomega ω
" iabbrev \upvarbeta ∂
" iabbrev \upvarepsilon ϵ
" iabbrev \upvartheta ϑ
" iabbrev \upvarkappa ϰ
" iabbrev \upphi ϕ
" iabbrev \upvarrho ϱ
" iabbrev \upvarpi ϖ
" iabbrev \upDigamma Ϝ
" iabbrev \updigamma ϝ
" 
" iabbrev \mbfAlpha 𝚨
" iabbrev \mbfBeta 𝚩
" iabbrev \mbfGamma 𝚪
" iabbrev \mbfDelta 𝚫
" iabbrev \mbfEpsilon 𝚬
" iabbrev \mbfZeta 𝚭
" iabbrev \mbfEta 𝚮
" iabbrev \mbfTheta 𝚯
" iabbrev \mbfIota 𝚰
" iabbrev \mbfKappa 𝚱
" iabbrev \mbfLambda 𝚲
" iabbrev \mbfMu 𝚳
" iabbrev \mbfNu 𝚴
" iabbrev \mbfXi 𝚵
" iabbrev \mbfOmicron 𝚶
" iabbrev \mbfPi 𝚷
" iabbrev \mbfRho 𝚸
" iabbrev \mbfvarTheta 𝚹
" iabbrev \mbfSigma 𝚺
" iabbrev \mbfTau 𝚻
" iabbrev \mbfUpsilon 𝚼
" iabbrev \mbfPhi 𝚽
" iabbrev \mbfChi 𝚾
" iabbrev \mbfPsi 𝚿
" iabbrev \mbfOmega 𝛀
" iabbrev \mbfnabla 𝛁
" iabbrev \mbfalpha 𝛂
" iabbrev \mbfbeta 𝛃
" iabbrev \mbfgamma 𝛄
" iabbrev \mbfdelta 𝛅
" iabbrev \mbfepsilon 𝛆
" iabbrev \mbfzeta 𝛇
" iabbrev \mbfeta 𝛈
" iabbrev \mbftheta 𝛉
" iabbrev \mbfiota 𝛊
" iabbrev \mbfkappa 𝛋
" iabbrev \mbflambda 𝛌
" iabbrev \mbfmu 𝛍
" iabbrev \mbfnu 𝛎
" iabbrev \mbfxi 𝛏
" iabbrev \mbfomicron 𝛐
" iabbrev \mbfpi 𝛑
" iabbrev \mbfrho 𝛒
" iabbrev \mbfvarsigma 𝛓
" iabbrev \mbfsigma 𝛔
" iabbrev \mbftau 𝛕
" iabbrev \mbfupsilon 𝛖
" iabbrev \mbfvarphi 𝛗
" iabbrev \mbfchi 𝛘
" iabbrev \mbfpsi 𝛙
" iabbrev \mbfomega 𝛚
" iabbrev \mbfpartial 𝛛
" iabbrev \mbfvarepsilon 𝛜
" iabbrev \mbfvartheta 𝛝
" iabbrev \mbfvarkappa 𝛞
" iabbrev \mbfphi 𝛟
" iabbrev \mbfvarrho 𝛠
" iabbrev \mbfvarpi 𝛡
" 
" iabbrev \mitAlpha 𝛢
" iabbrev \mitBeta 𝛣
" iabbrev \mitGamma 𝛤
" iabbrev \mitDelta 𝛥
" iabbrev \mitEpsilon 𝛦
" iabbrev \mitZeta 𝛧
" iabbrev \mitEta 𝛨
" iabbrev \mitTheta 𝛩
" iabbrev \mitIota 𝛪
" iabbrev \mitKappa 𝛫
" iabbrev \mitLambda 𝛬
" iabbrev \mitMu 𝛭
" iabbrev \mitNu 𝛮
" iabbrev \mitXi 𝛯
" iabbrev \mitOmicron 𝛰
" iabbrev \mitPi 𝛱
" iabbrev \mitRho 𝛲
" iabbrev \mitvarTheta 𝛳
" iabbrev \mitSigma 𝛴
" iabbrev \mitTau 𝛵
" iabbrev \mitUpsilon 𝛶
" iabbrev \mitPhi 𝛷
" iabbrev \mitChi 𝛸
" iabbrev \mitPsi 𝛹
" iabbrev \mitOmega 𝛺
" iabbrev \mitnabla 𝛻
" iabbrev \mitalpha 𝛼
" iabbrev \mitbeta 𝛽
" iabbrev \mitgamma 𝛾
" iabbrev \mitdelta 𝛿
" iabbrev \mitepsilon 𝜀
" iabbrev \mitzeta 𝜁
" iabbrev \miteta 𝜂
" iabbrev \mittheta 𝜃
" iabbrev \mitiota 𝜄
" iabbrev \mitkappa 𝜅
" iabbrev \mitlambda 𝜆
" iabbrev \mitmu 𝜇
" iabbrev \mitnu 𝜈
" iabbrev \mitxi 𝜉
" iabbrev \mitomicron 𝜊
" iabbrev \mitpi 𝜋
" iabbrev \mitrho 𝜌
" iabbrev \mitvarsigma 𝜍
" iabbrev \mitsigma 𝜎
" iabbrev \mittau 𝜏
" iabbrev \mitupsilon 𝜐
" iabbrev \mitphi 𝜑
" iabbrev \mitchi 𝜒
" iabbrev \mitpsi 𝜓
" iabbrev \mitomega 𝜔
" iabbrev \mitpartial 𝜕
" iabbrev \mitvarepsilon 𝜖
" iabbrev \mitvartheta 𝜗
" iabbrev \mitvarkappa 𝜘
" iabbrev \mitvarphi 𝜙
" iabbrev \mitvarrho 𝜚
" iabbrev \mitvarpi 𝜛
" 
" iabbrev \mbfitAlpha 𝜜
" iabbrev \mbfitBeta 𝜝
" iabbrev \mbfitGamma 𝜞
" iabbrev \mbfitDelta 𝜟
" iabbrev \mbfitEpsilon 𝜠
" iabbrev \mbfitZeta 𝜡
" iabbrev \mbfitEta 𝜢
" iabbrev \mbfitTheta 𝜣
" iabbrev \mbfitIota 𝜤
" iabbrev \mbfitKappa 𝜥
" iabbrev \mbfitLambda 𝜦
" iabbrev \mbfitMu 𝜧
" iabbrev \mbfitNu 𝜨
" iabbrev \mbfitXi 𝜩
" iabbrev \mbfitOmicron 𝜪
" iabbrev \mbfitPi 𝜫
" iabbrev \mbfitRho 𝜬
" iabbrev \mbfitvarTheta 𝜭
" iabbrev \mbfitSigma 𝜮
" iabbrev \mbfitTau 𝜯
" iabbrev \mbfitUpsilon 𝜰
" iabbrev \mbfitPhi 𝜱
" iabbrev \mbfitChi 𝜲
" iabbrev \mbfitPsi 𝜳
" iabbrev \mbfitOmega 𝜴
" iabbrev \mbfitnabla 𝜵
" iabbrev \mbfitalpha 𝜶
" iabbrev \mbfitbeta 𝜷
" iabbrev \mbfitgamma 𝜸
" iabbrev \mbfitdelta 𝜹
" iabbrev \mbfitepsilon 𝜺
" iabbrev \mbfitzeta 𝜻
" iabbrev \mbfiteta 𝜼
" iabbrev \mbfittheta 𝜽
" iabbrev \mbfitiota 𝜾
" iabbrev \mbfitkappa 𝜿
" iabbrev \mbfitlambda 𝝀
" iabbrev \mbfitmu 𝝁
" iabbrev \mbfitnu 𝝂
" iabbrev \mbfitxi 𝝃
" iabbrev \mbfitomicron 𝝄
" iabbrev \mbfitpi 𝝅
" iabbrev \mbfitrho 𝝆
" iabbrev \mbfitvarsigma 𝝇
" iabbrev \mbfitsigma 𝝈
" iabbrev \mbfittau 𝝉
" iabbrev \mbfitupsilon 𝝊
" iabbrev \mbfitphi 𝝋
" iabbrev \mbfitchi 𝝌
" iabbrev \mbfitpsi 𝝍
" iabbrev \mbfitomega 𝝎
" iabbrev \mbfitpartial 𝝏
" iabbrev \mbfitvarepsilon 𝝐
" iabbrev \mbfitvartheta 𝝑
" iabbrev \mbfitvarkappa 𝝒
" iabbrev \mbfitvarphi 𝝓
" iabbrev \mbfitvarrho 𝝔
" iabbrev \mbfitvarpi 𝝕
" 
" iabbrev \mbfsansAlpha 𝝖
" iabbrev \mbfsansBeta 𝝗
" iabbrev \mbfsansGamma 𝝘
" iabbrev \mbfsansDelta 𝝙
" iabbrev \mbfsansEpsilon 𝝚
" iabbrev \mbfsansZeta 𝝛
" iabbrev \mbfsansEta 𝝜
" iabbrev \mbfsansTheta 𝝝
" iabbrev \mbfsansIota 𝝞
" iabbrev \mbfsansKappa 𝝟
" iabbrev \mbfsansLambda 𝝠
" iabbrev \mbfsansMu 𝝡
" iabbrev \mbfsansNu 𝝢
" iabbrev \mbfsansXi 𝝣
" iabbrev \mbfsansOmicron 𝝤
" iabbrev \mbfsansPi 𝝥
" iabbrev \mbfsansRho 𝝦
" iabbrev \mbfsansvarTheta 𝝧
" iabbrev \mbfsansSigma 𝝨
" iabbrev \mbfsansTau 𝝩
" iabbrev \mbfsansUpsilon 𝝪
" iabbrev \mbfsansPhi 𝝫
" iabbrev \mbfsansChi 𝝬
" iabbrev \mbfsansPsi 𝝭
" iabbrev \mbfsansOmega 𝝮
" iabbrev \mbfsansnabla 𝝯
" iabbrev \mbfsansalpha 𝝰
" iabbrev \mbfsansbeta 𝝱
" iabbrev \mbfsansgamma 𝝲
" iabbrev \mbfsansdelta 𝝳
" iabbrev \mbfsansepsilon 𝝴
" iabbrev \mbfsanszeta 𝝵
" iabbrev \mbfsanseta 𝝶
" iabbrev \mbfsanstheta 𝝷
" iabbrev \mbfsansiota 𝝸
" iabbrev \mbfsanskappa 𝝹
" iabbrev \mbfsanslambda 𝝺
" iabbrev \mbfsansmu 𝝻
" iabbrev \mbfsansnu 𝝼
" iabbrev \mbfsansxi 𝝽
" iabbrev \mbfsansomicron 𝝾
" iabbrev \mbfsanspi 𝝿
" iabbrev \mbfsansrho 𝞀
" iabbrev \mbfsansvarsigma 𝞁
" iabbrev \mbfsanssigma 𝞂
" iabbrev \mbfsanstau 𝞃
" iabbrev \mbfsansupsilon 𝞄
" iabbrev \mbfsansphi 𝞅
" iabbrev \mbfsanschi 𝞆
" iabbrev \mbfsanspsi 𝞇
" iabbrev \mbfsansomega 𝞈
" iabbrev \mbfsanspartial 𝞉
" iabbrev \mbfsansvarepsilon 𝞊
" iabbrev \mbfsansvartheta 𝞋
" iabbrev \mbfsansvarkappa 𝞌
" iabbrev \mbfsansvarphi 𝞍
" iabbrev \mbfsansvarrho 𝞎
" iabbrev \mbfsansvarpi 𝞏
" 
" iabbrev \mbfitsansAlpha 𝞐
" iabbrev \mbfitsansBeta 𝞑
" iabbrev \mbfitsansGamma 𝞒
" iabbrev \mbfitsansDelta 𝞓
" iabbrev \mbfitsansEpsilon 𝞔
" iabbrev \mbfitsansZeta 𝞕
" iabbrev \mbfitsansEta 𝞖
" iabbrev \mbfitsansTheta 𝞗
" iabbrev \mbfitsansIota 𝞘
" iabbrev \mbfitsansKappa 𝞙
" iabbrev \mbfitsansLambda 𝞚
" iabbrev \mbfitsansMu 𝞛
" iabbrev \mbfitsansNu 𝞜
" iabbrev \mbfitsansXi 𝞝
" iabbrev \mbfitsansOmicron 𝞞
" iabbrev \mbfitsansPi 𝞟
" iabbrev \mbfitsansRho 𝞠
" iabbrev \mbfitsansvarTheta 𝞡
" iabbrev \mbfitsansSigma 𝞢
" iabbrev \mbfitsansTau 𝞣
" iabbrev \mbfitsansUpsilon 𝞤
" iabbrev \mbfitsansPhi 𝞥
" iabbrev \mbfitsansChi 𝞦
" iabbrev \mbfitsansPsi 𝞧
" iabbrev \mbfitsansOmega 𝞨
" iabbrev \mbfitsansnabla 𝞩
" iabbrev \mbfitsansalpha 𝞪
" iabbrev \mbfitsansbeta 𝞫
" iabbrev \mbfitsansgamma 𝞬
" iabbrev \mbfitsansdelta 𝞭
" iabbrev \mbfitsansepsilon 𝞮
" iabbrev \mbfitsanszeta 𝞯
" iabbrev \mbfitsanseta 𝞰
" iabbrev \mbfitsanstheta 𝞱
" iabbrev \mbfitsansiota 𝞲
" iabbrev \mbfitsanskappa 𝞳
" iabbrev \mbfitsanslambda 𝞴
" iabbrev \mbfitsansmu 𝞵
" iabbrev \mbfitsansnu 𝞶
" iabbrev \mbfitsansxi 𝞷
" iabbrev \mbfitsansomicron 𝞸
" iabbrev \mbfitsanspi 𝞹
" iabbrev \mbfitsansrho 𝞺
" iabbrev \mbfitsansvarsigma 𝞻
" iabbrev \mbfitsanssigma 𝞼
" iabbrev \mbfitsanstau 𝞽
" iabbrev \mbfitsansupsilon 𝞾
" iabbrev \mbfitsansphi 𝞿
" iabbrev \mbfitsanschi 𝟀
" iabbrev \mbfitsanspsi 𝟁
" iabbrev \mbfitsansomega 𝟂
" iabbrev \mbfitsanspartial 𝟃
" iabbrev \mbfitsansvarepsilon 𝟄
" iabbrev \mbfitsansvartheta 𝟅
" iabbrev \mbfitsansvarkappa 𝟆
" iabbrev \mbfitsansvarphi 𝟇
" iabbrev \mbfitsansvarrho 𝟈
" iabbrev \mbfitsansvarpi 𝟉
" 
" iabbrev \mfrakZ ℨ
" iabbrev \turnediota ℩
" iabbrev \aleph ℵ
" iabbrev \beth ℶ
" iabbrev \daleth ℸ
" iabbrev \Bbbgamma ℽ
" iabbrev \BbbGamma ℾ
" iabbrev \BbbPi ℿ
